########################
#   STAGING WORKFLOW   #
########################

# GENERAL PROCESS
# From your commcare-hq directory with the virtualenv turned on
# to safely push your changes to scripts/staging.yaml
#     $ scripts/commit-staging --push
# to rebuild from your new spec and deploy
#     $ scripts/rebuildstaging --deploy
# Both commands commands can be run without the flag as well.

# CONFLICT RESOLUTION
# First, determine where the conflict lies.
# a). branch `foo` conflicts with `master`
#       $ git checkout -b foo origin/foo
#       $ git pull origin master
#     try to resolve conflict
#       $ git push origin foo
# b). branch `foo` conflicts with branch `bar`
#     you can't just merge foo into bar or vice versa, otherwise the PR
#     for foo will contain commits from bar.  Instead make a third,
#     conflict-resolution branch:
#       $ git checkout -b foo+bar origin/foo
#       $ git pull origin bar
#     try to resolve conflict
#       $ git push origin foo+bar
#     add the branch `foo+bar` to staging.yaml and move branches foo and
#     bar to right below it
#
#     Later on branch B gets merged into master and removed from staging.yaml.
#     Perhaps the person who removes it also notices the A+B and does the
#     following. Otherwise anyone who comes along and sees A+B but not both
#     branches can feel free to assume the following need to be done.
#       * Merge A+B into A. Since B is now gone, you want to merge the
#         resolution into A, otherwise A will conflict with master.
#       * Remove A+B from staging.yaml. It's no longer necessary since it's
#         now a subset of A.
#
# If you are unsure of how to resolve a conflict, notify the branch owner.


trunk: master
name: autostaging
branches:
  - staging  # Ethan 11/09 - Too many effing merge conflicts
  - ptop-reindex  # DR 11/5
  - historical-forms  # DR 11/4
  - remove-hutch  # DR 10/28
#  - add-build-ui
#  - subscription-no-contact-info # bb 8/4
  - subscription-no-contact-info # bb 8/4
  - lwyszomi:better_date_filters_improvment
  # - lwyszomi:b3-mobile-layout
  - revert-4574-revert-4553-case-list-redesign # Noah 9/16
  - revert-4205-revert-3841-86347-2 # Daniel 9/11
  #- help-text # j$  10/8  removed 11/3 by Daniel
  - masterlist-workflow # j$  10/8
  - graphing+double-management # SK 10/3
  - double-management+case-detail-tabs2 # Noah 11/6
  - double-management # SK 10/15
  - bulk-app-translate # Noah 9/18
  - graphing # Nick P 10/27
  - case-detail-tabs # Noah 11/6
  - share-fixtures # j$ 10/29
  - logos # Nick P 10/31
  - hq-dropdown # sravan 5/7
  - 142623-jstree-upgrade # Daniel 11/3
  # - photo-export # J$ 11/4
  - fix-user-indicators # Nick P 11/5
  - custom-data-choices  # Ethan 11/09
submodules:
  submodules/couchlog-src:
    branches:
      - static-tags # Nick P 5/20
  submodules/django-prbac-src:
    branches:
      - memoize-perms # Sravan 11/9
  submodules/django-soil-src:
    branches:
      - static-tags # Nick P 5/20
  submodules/formtranslate-src:
    branches:
      - static-tags # Nick P 5/20
      # Danny 8/12. If form validation seems wonky on staging, just remove this
      - clean-up-api
  submodules/touchforms-src:
    branches:
      - static-tags # Nick P 5/20
#  submodules/dimagi-utils-src:
#    branches:
#      - json_response-status
  corehq/apps/hqmedia/static/hqmedia/MediaUploader:
    branches:
      - debug-yui # Nick P 11/4
